export enum MenuEnums {
  Inicio = 1,
  Empresas= 2,
  Usuarios= 3,
  Autrizaciones= 4,
  Roles= 5,
  Alertas= 6,
  Clientes= 7,
  ClientesServicios= 8,
  Facturacion= 9,
  FacturacionComplementos= 10,
  Lineas= 11,
  Servicios= 12,
  SubLineas= 13,
  TiposClientes= 14,
  Ventas= 15,
  VentasDetalles= 16,
  VentasPagos= 17,
  Tickets = 18,
}
