export const entidades = {
  AUTORIZACIONES: "AUTORIZACIONES",
  EMPRESAS: "EMPRESAS",
  ROLES: "ROLES",
  USUARIOS: "USUARIOS",
  CLIENTES: "CLIENTES",
  SERVICIOS: "FACTURACION",
  LINEAS: "LINEAS",
  SUBLINEAS: "SUBLINEAS",
  TIPOS_CLIENTES: "TIPOS_CLIENTES",
  ALERTAS: "ALERTAS",
  FACTURACION: "FACTURACION",
  TICKETS: "TICKETS",
};
